### PR TITLE
Update adam dependency version to 0.23.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by heuermh**
Jenkins build will fail due to https://github.com/bigdatagenomics/adam/issues/1578

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
@heuermh would you like to merge this and have a snapshot dependency on trunk, or keep this branch open until 0.23.0 is cut and then merge?

**Comment by heuermh** [comment]
Thanks for fixing the Jenkins problem upstream!  I'd prefer to merge this, otherwise I couldn't keep the branching for the other pull requests straight.

**Comment by fnothaft** [comment]
Sounds good to me. I've just merged this. Thanks @heuermh!

**Pull request merged**
